    gsDPPipeSync(),
    gsDPSetTextureLUT(G_TT_NONE),
    gsSPTexture(0x0BB8, 0x0BB8, 0, G_TX_RENDERTILE, G_ON),
    gsDPLoadTextureBlock_4b(gIronKnuckleTransformMetalTex, G_IM_FMT_I, gIronKnuckleTransformMetalTex_WIDTH, gIronKnuckleTransformMetalTex_HEIGHT,
 0, G_TX_MIRROR | G_TX_WRAP, G_TX_MIRROR | G_TX_WRAP, 5, 6, G_TX_NOLOD, G_TX_NOLOD),
    gsDPSetCombineLERP(PRIMITIVE, ENVIRONMENT, TEXEL0, ENVIRONMENT, 0, 0, 0, 0, COMBINED, 0, SHADE, 0, 0, 0, 0, ENVIRONMENT),
    gsDPSetRenderMode(G_RM_FOG_SHADE_A, G_RM_IK_TRANSFORM_XLU_SURF2),
    gsSPClearGeometryMode(G_CULL_BACK),
    gsSPSetGeometryMode(G_FOG | G_LIGHTING | G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR),
    gsDPSetPrimColor(0, 0, 255, 255, 255, 255),
    gsSPDisplayList(0x08000000),
    gsSPVertex(&gIronKnuckleTransformSplitHelmetRightVtx[0], 3, 0),
    gsSP1Triangle(0, 1, 2, 0),
    gsSPVertex(&gIronKnuckleTransformSplitHelmetRightVtx[3], 17, 0),
    gsSP2Triangles(0, 1, 2, 0, 0, 2, 3, 0),
    gsSP2Triangles(4, 0, 3, 0, 5, 6, 7, 0),
    gsSP2Triangles(8, 9, 10, 0, 11, 12, 13, 0),
    gsSP2Triangles(6, 5, 9, 0, 11, 14, 12, 0),
    gsSP2Triangles(10, 15, 8, 0, 9, 5, 10, 0),
    gsSP1Triangle(13, 16, 11, 0),
    gsDPPipeSync(),
    gsSPDisplayList(0x0A000000),
    gsSPVertex(&gIronKnuckleTransformSplitHelmetRightVtx[20], 7, 0),
    gsSP2Triangles(0, 1, 2, 0, 0, 2, 3, 0),
    gsSP2Triangles(4, 5, 6, 0, 6, 0, 4, 0),
    gsSP1Triangle(4, 0, 3, 0),
    gsDPPipeSync(),
    gsSPTexture(0xFFFF, 0xFFFF, 0, G_TX_RENDERTILE, G_ON),
    gsDPLoadTextureBlock(gIronKnuckleTransformBlockPatternTex, G_IM_FMT_RGBA, G_IM_SIZ_16b, gIronKnuckleTransformBlockPatternTex_WIDTH,
 gIronKnuckleTransformBlockPatternTex_HEIGHT, 0, G_TX_NOMIRROR | G_TX_WRAP, G_TX_NOMIRROR | G_TX_CLAMP, 4, 4, G_TX_NOLOD,
 G_TX_NOLOD),
    gsDPSetCombineLERP(TEXEL0, 0, SHADE, 0, 0, 0, 0, ENVIRONMENT, COMBINED, 0, PRIMITIVE, 0, 0, 0, 0, COMBINED),
    gsDPSetRenderMode(G_RM_FOG_SHADE_A, G_RM_IK_TRANSFORM_XLU_SURF2),
    gsSPClearGeometryMode(G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR),
    gsDPSetPrimColor(0, 0, 255, 255, 255, 255),
    gsSPVertex(&gIronKnuckleTransformSplitHelmetRightVtx[27], 8, 0),
    gsSP2Triangles(0, 1, 2, 0, 0, 3, 4, 0),
    gsSP2Triangles(3, 5, 4, 0, 1, 0, 4, 0),
    gsSP2Triangles(1, 6, 7, 0, 1, 4, 6, 0),
    gsSP1Triangle(6, 4, 5, 0),
    gsDPPipeSync(),
    gsDPLoadTextureBlock(gIronKnuckleTransformChainMailTex, G_IM_FMT_RGBA, G_IM_SIZ_16b, gIronKnuckleTransformChainMailTex_WIDTH,
 gIronKnuckleTransformChainMailTex_HEIGHT, 0, G_TX_NOMIRROR | G_TX_WRAP, G_TX_NOMIRROR | G_TX_CLAMP, 4, 4, G_TX_NOLOD,
 G_TX_NOLOD),
    gsSPVertex(&gIronKnuckleTransformSplitHelmetRightVtx[35], 9, 0),
    gsSP2Triangles(0, 1, 2, 0, 2, 3, 4, 0),
    gsSP2Triangles(3, 5, 4, 0, 0, 2, 4, 0),
    gsSP2Triangles(3, 6, 5, 0, 0, 7, 8, 0),
    gsSP1Triangle(0, 8, 1, 0),
    gsSPEndDisplayList(),
