    gsDPPipeSync(),
    gsDPSetTextureLUT(G_TT_NONE),
    gsSPTexture(0x0BB8, 0x0BB8, 0, G_TX_RENDERTILE, G_ON),
    gsDPLoadTextureBlock_4b(gIronKnuckleTransformMetalTex, G_IM_FMT_I, gIronKnuckleTransformMetalTex_WIDTH, gIronKnuckleTransformMetalTex_HEIGHT,
 0, G_TX_MIRROR | G_TX_WRAP, G_TX_MIRROR | G_TX_WRAP, 5, 6, G_TX_NOLOD, G_TX_NOLOD),
    gsDPSetCombineLERP(PRIMITIVE, ENVIRONMENT, TEXEL0, ENVIRONMENT, 0, 0, 0, 0, COMBINED, 0, SHADE, 0, 0, 0, 0, ENVIRONMENT),
    gsDPSetRenderMode(G_RM_FOG_SHADE_A, G_RM_AA_ZB_XLU_SURF2),
    gsSPClearGeometryMode(G_CULL_BACK),
    gsSPSetGeometryMode(G_FOG | G_LIGHTING | G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR),
    gsDPSetPrimColor(0, 0, 255, 255, 255, 255),
    gsSPDisplayList(0x08000000),
    gsSPVertex(&gIronKnuckleTransformSplitHelmetLeftVtx[0], 3, 0),
    gsSP1Triangle(0, 1, 2, 0),
    gsSPVertex(&gIronKnuckleTransformSplitHelmetLeftVtx[3], 23, 0),
    gsSP2Triangles(0, 1, 2, 0, 1, 3, 2, 0),
    gsSP2Triangles(2, 3, 4, 0, 5, 6, 7, 0),
    gsSP2Triangles(8, 9, 10, 0, 11, 12, 9, 0),
    gsSP2Triangles(8, 11, 9, 0, 9, 12, 13, 0),
    gsSP2Triangles(13, 10, 9, 0, 14, 15, 16, 0),
    gsSP2Triangles(7, 6, 14, 0, 17, 18, 19, 0),
    gsSP2Triangles(17, 20, 18, 0, 16, 15, 21, 0),
    gsSP2Triangles(7, 14, 16, 0, 19, 18, 22, 0),
    gsDPPipeSync(),
    gsSPDisplayList(0x0A000000),
    gsSPVertex(&gIronKnuckleTransformSplitHelmetLeftVtx[26], 5, 0),
    gsSP2Triangles(0, 1, 2, 0, 0, 3, 1, 0),
    gsSP1Triangle(4, 3, 0, 0),
    gsDPPipeSync(),
    gsSPSetGeometryMode(G_CULL_BACK),
    gsSPVertex(&gIronKnuckleTransformSplitHelmetLeftVtx[31], 4, 0),
    gsSP2Triangles(0, 1, 2, 0, 0, 3, 1, 0),
    gsDPPipeSync(),
    gsSPTexture(0xFFFF, 0xFFFF, 0, G_TX_RENDERTILE, G_ON),
    gsDPLoadTextureBlock(gIronKnuckleTransformBlockPatternTex, G_IM_FMT_RGBA, G_IM_SIZ_16b, gIronKnuckleTransformBlockPatternTex_WIDTH,
 gIronKnuckleTransformBlockPatternTex_HEIGHT, 0, G_TX_NOMIRROR | G_TX_WRAP, G_TX_NOMIRROR | G_TX_CLAMP, 4, 4, G_TX_NOLOD,
 G_TX_NOLOD),
    gsDPSetCombineLERP(TEXEL0, 0, SHADE, 0, 0, 0, 0, ENVIRONMENT, COMBINED, 0, PRIMITIVE, 0, 0, 0, 0, COMBINED),
    gsDPSetRenderMode(G_RM_FOG_SHADE_A, G_RM_AA_ZB_XLU_SURF2),
    gsSPClearGeometryMode(G_CULL_BACK | G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR),
    gsDPSetPrimColor(0, 0, 255, 255, 255, 255),
    gsSPVertex(&gIronKnuckleTransformSplitHelmetLeftVtx[35], 7, 0),
    gsSP2Triangles(0, 1, 2, 0, 1, 3, 2, 0),
    gsSP2Triangles(4, 1, 0, 0, 5, 6, 4, 0),
    gsSP2Triangles(6, 1, 4, 0, 6, 3, 1, 0),
    gsDPPipeSync(),
    gsDPLoadTextureBlock(gIronKnuckleTransformChainMailTex, G_IM_FMT_RGBA, G_IM_SIZ_16b, gIronKnuckleTransformChainMailTex_WIDTH,
 gIronKnuckleTransformChainMailTex_HEIGHT, 0, G_TX_NOMIRROR | G_TX_WRAP, G_TX_NOMIRROR | G_TX_CLAMP, 4, 4, G_TX_NOLOD,
 G_TX_NOLOD),
    gsSPVertex(&gIronKnuckleTransformSplitHelmetLeftVtx[42], 8, 0),
    gsSP2Triangles(0, 1, 2, 0, 3, 4, 5, 0),
    gsSP2Triangles(3, 0, 4, 0, 4, 0, 2, 0),
    gsSP2Triangles(1, 6, 7, 0, 1, 7, 2, 0),
    gsDPPipeSync(),
    gsDPSetTextureLUT(G_TT_RGBA16),
    gsDPLoadTextureBlock(gIronKnuckleTransformJewelTex, G_IM_FMT_CI, G_IM_SIZ_8b, gIronKnuckleTransformJewelTex_WIDTH,
 gIronKnuckleTransformJewelTex_HEIGHT, 0, G_TX_NOMIRROR | G_TX_CLAMP, G_TX_NOMIRROR | G_TX_CLAMP, 4, 4, G_TX_NOLOD, G_TX_NOLOD),
    gsDPLoadTLUT_pal256(object_ik_transform_Tlut_00F630),
    gsSPVertex(&gIronKnuckleTransformSplitHelmetLeftVtx[50], 5, 0),
    gsSP2Triangles(0, 1, 2, 0, 0, 2, 3, 0),
    gsSP2Triangles(3, 2, 4, 0, 2, 1, 4, 0),
    gsSPEndDisplayList(),
