    gsDPPipeSync(),
    gsDPSetTextureLUT(G_TT_RGBA16),
    gsSPTexture(0xFFFF, 0xFFFF, 0, G_TX_RENDERTILE, G_ON),
    gsDPLoadTextureBlock(object_ik_transform_Tex_017378, G_IM_FMT_CI, G_IM_SIZ_8b, object_ik_transform_Tex_017378_WIDTH,
 object_ik_transform_Tex_017378_HEIGHT, 0, G_TX_NOMIRROR | G_TX_CLAMP, G_TX_NOMIRROR | G_TX_CLAMP, 4, 4, G_TX_NOLOD, G_TX_NOLOD),
    gsDPLoadTLUT_pal256(object_ik_transform_Tlut_017288),
    gsDPSetCombineLERP(TEXEL0, 0, SHADE, 0, 0, 0, 0, ENVIRONMENT, COMBINED, 0, PRIMITIVE, 0, 0, 0, 0, COMBINED),
    gsDPSetRenderMode(G_RM_FOG_SHADE_A, G_RM_IK_TRANSFORM_XLU_SURF2),
    gsSPClearGeometryMode(G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR),
    gsSPSetGeometryMode(G_CULL_BACK | G_FOG | G_LIGHTING),
    gsDPSetPrimColor(0, 0, 255, 255, 255, 255),
    gsSPVertex(&gIronKnuckleTransformGerudoHeadVtx[0], 11, 0),
    gsSP2Triangles(0, 1, 2, 0, 3, 1, 4, 0),
    gsSP2Triangles(5, 6, 7, 0, 8, 9, 10, 0),
    gsDPPipeSync(),
    gsDPSetTextureLUT(G_TT_NONE),
    gsDPLoadTextureBlock(gIronKnuckleTransformGerudoEyeTex, G_IM_FMT_RGBA, G_IM_SIZ_16b, gIronKnuckleTransformGerudoEyeTex_WIDTH,
 gIronKnuckleTransformGerudoEyeTex_HEIGHT, 0, G_TX_NOMIRROR | G_TX_CLAMP, G_TX_NOMIRROR | G_TX_CLAMP, 5, 5, G_TX_NOLOD,
 G_TX_NOLOD),
    gsSPVertex(&gIronKnuckleTransformGerudoHeadVtx[11], 5, 0),
    gsSP2Triangles(0, 1, 2, 0, 0, 3, 1, 0),
    gsSP1Triangle(3, 4, 1, 0),
    gsDPPipeSync(),
    gsDPSetTextureLUT(G_TT_RGBA16),
    gsDPLoadTextureBlock(object_ik_transform_Tex_017478, G_IM_FMT_CI, G_IM_SIZ_8b, object_ik_transform_Tex_017478_WIDTH,
 object_ik_transform_Tex_017478_HEIGHT, 0, G_TX_NOMIRROR | G_TX_WRAP, G_TX_NOMIRROR | G_TX_CLAMP, 3, 3, G_TX_NOLOD, G_TX_NOLOD),
    gsDPLoadTLUT_pal256(object_ik_transform_Tlut_017288),
    gsSPVertex(&gIronKnuckleTransformGerudoHeadVtx[16], 8, 0),
    gsSP2Triangles(0, 1, 2, 0, 0, 2, 3, 0),
    gsSP2Triangles(4, 5, 6, 0, 7, 4, 6, 0),
    gsDPPipeSync(),
    gsDPSetTextureLUT(G_TT_NONE),
    gsDPLoadTextureBlock(gIronKnuckleTransformGerudoEyeTex, G_IM_FMT_RGBA, G_IM_SIZ_16b, gIronKnuckleTransformGerudoEyeTex_WIDTH,
 gIronKnuckleTransformGerudoEyeTex_HEIGHT, 0, G_TX_NOMIRROR | G_TX_CLAMP, G_TX_NOMIRROR | G_TX_CLAMP, 5, 5, G_TX_NOLOD,
 G_TX_NOLOD),
    gsSPVertex(&gIronKnuckleTransformGerudoHeadVtx[24], 5, 0),
    gsSP2Triangles(0, 1, 2, 0, 3, 0, 2, 0),
    gsSP1Triangle(0, 4, 1, 0),
    gsDPPipeSync(),
    gsDPSetTextureLUT(G_TT_RGBA16),
    gsDPLoadTextureBlock(object_ik_transform_Tex_017478, G_IM_FMT_CI, G_IM_SIZ_8b, object_ik_transform_Tex_017478_WIDTH,
 object_ik_transform_Tex_017478_HEIGHT, 0, G_TX_NOMIRROR | G_TX_WRAP, G_TX_NOMIRROR | G_TX_CLAMP, 3, 3, G_TX_NOLOD, G_TX_NOLOD),
    gsDPLoadTLUT_pal256(object_ik_transform_Tlut_017288),
    gsSPVertex(&gIronKnuckleTransformGerudoHeadVtx[29], 3, 0),
    gsSP1Triangle(0, 1, 2, 0),
    gsDPPipeSync(),
    gsDPLoadTextureBlock(object_ik_transform_Tex_0176B8, G_IM_FMT_CI, G_IM_SIZ_8b, object_ik_transform_Tex_0176B8_WIDTH,
 object_ik_transform_Tex_0176B8_HEIGHT, 0, G_TX_NOMIRROR | G_TX_CLAMP, G_TX_NOMIRROR | G_TX_CLAMP, 4, 4, G_TX_NOLOD, G_TX_NOLOD),
    gsSPVertex(&gIronKnuckleTransformGerudoHeadVtx[32], 3, 0),
    gsSP1Triangle(0, 1, 2, 0),
    gsDPPipeSync(),
    gsDPLoadTextureBlock(object_ik_transform_Tex_017478, G_IM_FMT_CI, G_IM_SIZ_8b, object_ik_transform_Tex_017478_WIDTH,
 object_ik_transform_Tex_017478_HEIGHT, 0, G_TX_NOMIRROR | G_TX_WRAP, G_TX_NOMIRROR | G_TX_CLAMP, 3, 3, G_TX_NOLOD, G_TX_NOLOD),
    gsSPVertex(&gIronKnuckleTransformGerudoHeadVtx[35], 3, 0),
    gsSP1Triangle(0, 1, 2, 0),
    gsDPPipeSync(),
    gsDPLoadTextureBlock(object_ik_transform_Tex_0176B8, G_IM_FMT_CI, G_IM_SIZ_8b, object_ik_transform_Tex_0176B8_WIDTH,
 object_ik_transform_Tex_0176B8_HEIGHT, 0, G_TX_NOMIRROR | G_TX_CLAMP, G_TX_NOMIRROR | G_TX_CLAMP, 4, 4, G_TX_NOLOD, G_TX_NOLOD),
    gsSPVertex(&gIronKnuckleTransformGerudoHeadVtx[38], 3, 0),
    gsSP1Triangle(0, 1, 2, 0),
    gsDPPipeSync(),
    gsDPLoadTextureBlock(gIronKnuckleTransformHair2Tex, G_IM_FMT_CI, G_IM_SIZ_8b, gIronKnuckleTransformHair2Tex_WIDTH,
 gIronKnuckleTransformHair2Tex_HEIGHT, 0, G_TX_NOMIRROR | G_TX_WRAP, G_TX_NOMIRROR | G_TX_CLAMP, 4, 4, G_TX_NOLOD, G_TX_NOLOD),
    gsSPVertex(&gIronKnuckleTransformGerudoHeadVtx[41], 8, 0),
    gsSP2Triangles(0, 1, 2, 0, 3, 0, 2, 0),
    gsSP2Triangles(4, 5, 6, 0, 4, 7, 5, 0),
    gsDPPipeSync(),
    gsDPLoadTextureBlock(object_ik_transform_Tex_017478, G_IM_FMT_CI, G_IM_SIZ_8b, object_ik_transform_Tex_017478_WIDTH,
 object_ik_transform_Tex_017478_HEIGHT, 0, G_TX_NOMIRROR | G_TX_WRAP, G_TX_NOMIRROR | G_TX_CLAMP, 3, 3, G_TX_NOLOD, G_TX_NOLOD),
    gsSPVertex(&gIronKnuckleTransformGerudoHeadVtx[49], 12, 0),
    gsSP2Triangles(0, 1, 2, 0, 3, 4, 5, 0),
    gsSP2Triangles(6, 7, 8, 0, 9, 10, 11, 0),
    gsDPPipeSync(),
    gsDPSetTextureLUT(G_TT_NONE),
    gsDPLoadTextureBlock(gIronKnuckleTransformChainMailTex, G_IM_FMT_RGBA, G_IM_SIZ_16b, gIronKnuckleTransformChainMailTex_WIDTH,
 gIronKnuckleTransformChainMailTex_HEIGHT, 0, G_TX_NOMIRROR | G_TX_WRAP, G_TX_NOMIRROR | G_TX_CLAMP, 4, 4, G_TX_NOLOD,
 G_TX_NOLOD),
    gsSPVertex(&gIronKnuckleTransformGerudoHeadVtx[61], 6, 0),
    gsSP2Triangles(0, 1, 2, 0, 3, 4, 5, 0),
    gsDPPipeSync(),
    gsDPSetTextureLUT(G_TT_RGBA16),
    gsDPLoadTextureBlock(object_ik_transform_Tex_017478, G_IM_FMT_CI, G_IM_SIZ_8b, object_ik_transform_Tex_017478_WIDTH,
 object_ik_transform_Tex_017478_HEIGHT, 0, G_TX_NOMIRROR | G_TX_WRAP, G_TX_NOMIRROR | G_TX_CLAMP, 3, 3, G_TX_NOLOD, G_TX_NOLOD),
    gsDPLoadTLUT_pal256(object_ik_transform_Tlut_017288),
    gsSPVertex(&gIronKnuckleTransformGerudoHeadVtx[67], 4, 0),
    gsSP2Triangles(0, 1, 2, 0, 2, 1, 3, 0),
    gsDPPipeSync(),
    gsDPSetTextureLUT(G_TT_NONE),
    gsSPTexture(0, 0, 0, G_TX_RENDERTILE, G_OFF),
    gsDPSetCombineLERP(SHADE, 0, PRIMITIVE, 0, 0, 0, 0, ENVIRONMENT, 0, 0, 0, COMBINED, 0, 0, 0, COMBINED),
    gsSPClearGeometryMode(G_CULL_BACK),
    gsDPSetPrimColor(0, 0, 243, 243, 0, 255),
    gsSPVertex(&gIronKnuckleTransformGerudoHeadVtx[71], 10, 0),
    gsSP2Triangles(0, 1, 2, 0, 0, 2, 3, 0),
    gsSP2Triangles(1, 4, 5, 0, 1, 5, 2, 0),
    gsSP2Triangles(4, 6, 7, 0, 4, 7, 5, 0),
    gsSP2Triangles(8, 9, 0, 0, 8, 0, 3, 0),
    gsSP2Triangles(6, 9, 8, 0, 6, 8, 7, 0),
    gsDPPipeSync(),
    gsDPSetTextureLUT(G_TT_RGBA16),
    gsSPTexture(0xFFFF, 0xFFFF, 0, G_TX_RENDERTILE, G_ON),
    gsDPLoadTextureBlock(object_ik_transform_Tex_0175B8, G_IM_FMT_CI, G_IM_SIZ_8b, object_ik_transform_Tex_0175B8_WIDTH,
 object_ik_transform_Tex_0175B8_HEIGHT, 0, G_TX_NOMIRROR | G_TX_CLAMP, G_TX_NOMIRROR | G_TX_CLAMP, 3, 4, G_TX_NOLOD, G_TX_NOLOD),
    gsDPLoadTLUT_pal256(object_ik_transform_Tlut_017288),
    gsDPSetCombineLERP(TEXEL0, 0, SHADE, 0, 0, 0, 0, ENVIRONMENT, COMBINED, 0, PRIMITIVE, 0, 0, 0, 0, COMBINED),
    gsDPSetPrimColor(0, 0, 255, 255, 255, 255),
    gsSPVertex(&gIronKnuckleTransformGerudoHeadVtx[81], 4, 0),
    gsSP2Triangles(0, 1, 2, 0, 3, 0, 2, 0),
    gsDPPipeSync(),
    gsDPLoadTextureBlock(object_ik_transform_Tex_017478, G_IM_FMT_CI, G_IM_SIZ_8b, object_ik_transform_Tex_017478_WIDTH,
 object_ik_transform_Tex_017478_HEIGHT, 0, G_TX_NOMIRROR | G_TX_WRAP, G_TX_NOMIRROR | G_TX_CLAMP, 3, 3, G_TX_NOLOD, G_TX_NOLOD),
    gsSPVertex(&gIronKnuckleTransformGerudoHeadVtx[85], 3, 0),
    gsSP1Triangle(0, 1, 2, 0),
    gsDPPipeSync(),
    gsSPSetGeometryMode(G_CULL_BACK),
    gsSPVertex(&gIronKnuckleTransformGerudoHeadVtx[88], 3, 0),
    gsSP1Triangle(0, 1, 2, 0),
    gsDPPipeSync(),
    gsDPSetTextureLUT(G_TT_NONE),
    gsSPTexture(0, 0, 0, G_TX_RENDERTILE, G_OFF),
    gsDPSetCombineLERP(SHADE, 0, PRIMITIVE, 0, 0, 0, 0, ENVIRONMENT, 0, 0, 0, COMBINED, 0, 0, 0, COMBINED),
    gsSPClearGeometryMode(G_CULL_BACK),
    gsDPSetPrimColor(0, 0, 243, 243, 0, 255),
    gsSPVertex(&gIronKnuckleTransformGerudoHeadVtx[91], 10, 0),
    gsSP2Triangles(0, 1, 2, 0, 0, 2, 3, 0),
    gsSP2Triangles(4, 0, 3, 0, 4, 3, 5, 0),
    gsSP2Triangles(6, 4, 5, 0, 6, 5, 7, 0),
    gsSP2Triangles(8, 6, 7, 0, 8, 7, 9, 0),
    gsSP2Triangles(8, 9, 2, 0, 8, 2, 1, 0),
    gsDPPipeSync(),
    gsDPSetTextureLUT(G_TT_RGBA16),
    gsSPTexture(0xFFFF, 0xFFFF, 0, G_TX_RENDERTILE, G_ON),
    gsDPLoadTextureBlock(object_ik_transform_Tex_017478, G_IM_FMT_CI, G_IM_SIZ_8b, object_ik_transform_Tex_017478_WIDTH,
 object_ik_transform_Tex_017478_HEIGHT, 0, G_TX_NOMIRROR | G_TX_WRAP, G_TX_NOMIRROR | G_TX_CLAMP, 3, 3, G_TX_NOLOD, G_TX_NOLOD),
    gsDPLoadTLUT_pal256(object_ik_transform_Tlut_017288),
    gsDPSetCombineLERP(TEXEL0, 0, SHADE, 0, 0, 0, 0, ENVIRONMENT, COMBINED, 0, PRIMITIVE, 0, 0, 0, 0, COMBINED),
    gsDPSetPrimColor(0, 0, 255, 255, 255, 255),
    gsSPVertex(&gIronKnuckleTransformGerudoHeadVtx[101], 3, 0),
    gsSP1Triangle(0, 1, 2, 0),
    gsDPPipeSync(),
    gsDPLoadTextureBlock(object_ik_transform_Tex_0175B8, G_IM_FMT_CI, G_IM_SIZ_8b, object_ik_transform_Tex_0175B8_WIDTH,
 object_ik_transform_Tex_0175B8_HEIGHT, 0, G_TX_NOMIRROR | G_TX_CLAMP, G_TX_NOMIRROR | G_TX_CLAMP, 3, 4, G_TX_NOLOD, G_TX_NOLOD),
    gsSPVertex(&gIronKnuckleTransformGerudoHeadVtx[104], 4, 0),
    gsSP2Triangles(0, 1, 2, 0, 0, 3, 1, 0),
    gsDPPipeSync(),
    gsDPLoadTextureBlock(object_ik_transform_Tex_017478, G_IM_FMT_CI, G_IM_SIZ_8b, object_ik_transform_Tex_017478_WIDTH,
 object_ik_transform_Tex_017478_HEIGHT, 0, G_TX_NOMIRROR | G_TX_WRAP, G_TX_NOMIRROR | G_TX_CLAMP, 3, 3, G_TX_NOLOD, G_TX_NOLOD),
    gsSPSetGeometryMode(G_CULL_BACK),
    gsSPVertex(&gIronKnuckleTransformGerudoHeadVtx[108], 10, 0),
    gsSP2Triangles(0, 1, 2, 0, 3, 4, 5, 0),
    gsSP2Triangles(6, 7, 8, 0, 6, 8, 9, 0),
    gsDPPipeSync(),
    gsDPSetTextureLUT(G_TT_NONE),
    gsDPLoadTextureBlock(gIronKnuckleTransformChainMailTex, G_IM_FMT_RGBA, G_IM_SIZ_16b, gIronKnuckleTransformChainMailTex_WIDTH,
 gIronKnuckleTransformChainMailTex_HEIGHT, 0, G_TX_NOMIRROR | G_TX_WRAP, G_TX_NOMIRROR | G_TX_CLAMP, 4, 4, G_TX_NOLOD,
 G_TX_NOLOD),
    gsSPVertex(&gIronKnuckleTransformGerudoHeadVtx[118], 15, 0),
    gsSP2Triangles(0, 1, 2, 0, 3, 4, 5, 0),
    gsSP2Triangles(6, 4, 3, 0, 6, 3, 2, 0),
    gsSP2Triangles(1, 6, 2, 0, 7, 8, 9, 0),
    gsSP2Triangles(10, 11, 12, 0, 10, 12, 8, 0),
    gsSP2Triangles(10, 13, 11, 0, 14, 11, 13, 0),
    gsDPPipeSync(),
    gsDPSetTextureLUT(G_TT_RGBA16),
    gsDPLoadTextureBlock(gIronKnuckleTransformHair2Tex, G_IM_FMT_CI, G_IM_SIZ_8b, gIronKnuckleTransformHair2Tex_WIDTH,
 gIronKnuckleTransformHair2Tex_HEIGHT, 0, G_TX_NOMIRROR | G_TX_WRAP, G_TX_NOMIRROR | G_TX_CLAMP, 4, 4, G_TX_NOLOD, G_TX_NOLOD),
    gsDPLoadTLUT_pal256(object_ik_transform_Tlut_017288),
    gsSPVertex(&gIronKnuckleTransformGerudoHeadVtx[133], 14, 0),
    gsSP2Triangles(0, 1, 2, 0, 0, 2, 3, 0),
    gsSP2Triangles(4, 0, 3, 0, 5, 6, 7, 0),
    gsSP2Triangles(8, 9, 10, 0, 11, 12, 13, 0),
    gsDPPipeSync(),
    gsDPSetTextureLUT(G_TT_NONE),
    gsDPLoadTextureBlock(gIronKnuckleTransformChainMailTex, G_IM_FMT_RGBA, G_IM_SIZ_16b, gIronKnuckleTransformChainMailTex_WIDTH,
 gIronKnuckleTransformChainMailTex_HEIGHT, 0, G_TX_NOMIRROR | G_TX_WRAP, G_TX_NOMIRROR | G_TX_CLAMP, 4, 4, G_TX_NOLOD,
 G_TX_NOLOD),
    gsSPVertex(&gIronKnuckleTransformGerudoHeadVtx[147], 27, 0),
    gsSP2Triangles(0, 1, 2, 0, 3, 4, 5, 0),
    gsSP2Triangles(6, 7, 8, 0, 9, 7, 6, 0),
    gsSP2Triangles(6, 8, 10, 0, 11, 12, 13, 0),
    gsSP2Triangles(14, 15, 16, 0, 17, 18, 19, 0),
    gsSP2Triangles(20, 21, 22, 0, 19, 23, 17, 0),
    gsSP1Triangle(24, 25, 26, 0),
    gsDPPipeSync(),
    gsDPSetTextureLUT(G_TT_RGBA16),
    gsDPLoadTextureBlock(gIronKnuckleTransformHair2Tex, G_IM_FMT_CI, G_IM_SIZ_8b, gIronKnuckleTransformHair2Tex_WIDTH,
 gIronKnuckleTransformHair2Tex_HEIGHT, 0, G_TX_NOMIRROR | G_TX_WRAP, G_TX_NOMIRROR | G_TX_CLAMP, 4, 4, G_TX_NOLOD, G_TX_NOLOD),
    gsDPLoadTLUT_pal256(object_ik_transform_Tlut_017288),
    gsSPVertex(&gIronKnuckleTransformGerudoHeadVtx[174], 3, 0),
    gsSP1Triangle(0, 1, 2, 0),
    gsDPPipeSync(),
    gsDPSetTextureLUT(G_TT_NONE),
    gsDPLoadTextureBlock(gIronKnuckleTransformChainMailTex, G_IM_FMT_RGBA, G_IM_SIZ_16b, gIronKnuckleTransformChainMailTex_WIDTH,
 gIronKnuckleTransformChainMailTex_HEIGHT, 0, G_TX_NOMIRROR | G_TX_WRAP, G_TX_NOMIRROR | G_TX_CLAMP, 4, 4, G_TX_NOLOD,
 G_TX_NOLOD),
    gsSPVertex(&gIronKnuckleTransformGerudoHeadVtx[177], 9, 0),
    gsSP2Triangles(0, 1, 2, 0, 3, 4, 5, 0),
    gsSP1Triangle(6, 7, 8, 0),
    gsDPPipeSync(),
    gsDPSetTextureLUT(G_TT_RGBA16),
    gsDPLoadTextureBlock(gIronKnuckleTransformHair2Tex, G_IM_FMT_CI, G_IM_SIZ_8b, gIronKnuckleTransformHair2Tex_WIDTH,
 gIronKnuckleTransformHair2Tex_HEIGHT, 0, G_TX_NOMIRROR | G_TX_WRAP, G_TX_NOMIRROR | G_TX_CLAMP, 4, 4, G_TX_NOLOD, G_TX_NOLOD),
    gsDPLoadTLUT_pal256(object_ik_transform_Tlut_017288),
    gsSPVertex(&gIronKnuckleTransformGerudoHeadVtx[186], 3, 0),
    gsSP1Triangle(0, 1, 2, 0),
    gsDPPipeSync(),
    gsDPSetTextureLUT(G_TT_NONE),
    gsDPLoadTextureBlock(gIronKnuckleTransformChainMailTex, G_IM_FMT_RGBA, G_IM_SIZ_16b, gIronKnuckleTransformChainMailTex_WIDTH,
 gIronKnuckleTransformChainMailTex_HEIGHT, 0, G_TX_NOMIRROR | G_TX_WRAP, G_TX_NOMIRROR | G_TX_CLAMP, 4, 4, G_TX_NOLOD,
 G_TX_NOLOD),
    gsSPVertex(&gIronKnuckleTransformGerudoHeadVtx[189], 9, 0),
    gsSP2Triangles(0, 1, 2, 0, 3, 4, 5, 0),
    gsSP1Triangle(6, 7, 8, 0),
    gsDPPipeSync(),
    gsDPSetTextureLUT(G_TT_RGBA16),
    gsDPLoadTextureBlock(object_ik_transform_Tex_017478, G_IM_FMT_CI, G_IM_SIZ_8b, object_ik_transform_Tex_017478_WIDTH,
 object_ik_transform_Tex_017478_HEIGHT, 0, G_TX_NOMIRROR | G_TX_WRAP, G_TX_NOMIRROR | G_TX_CLAMP, 3, 3, G_TX_NOLOD, G_TX_NOLOD),
    gsDPLoadTLUT_pal256(object_ik_transform_Tlut_017288),
    gsSPVertex(&gIronKnuckleTransformGerudoHeadVtx[198], 3, 0),
    gsSP1Triangle(0, 1, 2, 0),
    gsDPPipeSync(),
    gsDPSetTextureLUT(G_TT_NONE),
    gsDPLoadTextureBlock(gIronKnuckleTransformChainMailTex, G_IM_FMT_RGBA, G_IM_SIZ_16b, gIronKnuckleTransformChainMailTex_WIDTH,
 gIronKnuckleTransformChainMailTex_HEIGHT, 0, G_TX_NOMIRROR | G_TX_WRAP, G_TX_NOMIRROR | G_TX_CLAMP, 4, 4, G_TX_NOLOD,
 G_TX_NOLOD),
    gsSPVertex(&gIronKnuckleTransformGerudoHeadVtx[201], 3, 0),
    gsSP1Triangle(0, 1, 2, 0),
    gsDPPipeSync(),
    gsDPSetTextureLUT(G_TT_RGBA16),
    gsDPLoadTextureBlock(object_ik_transform_Tex_017638, G_IM_FMT_CI, G_IM_SIZ_8b, object_ik_transform_Tex_017638_WIDTH,
 object_ik_transform_Tex_017638_HEIGHT, 0, G_TX_MIRROR | G_TX_WRAP, G_TX_NOMIRROR | G_TX_CLAMP, 3, 4, G_TX_NOLOD, G_TX_NOLOD),
    gsDPLoadTLUT_pal256(object_ik_transform_Tlut_017288),
    gsSPVertex(&gIronKnuckleTransformGerudoHeadVtx[204], 4, 0),
    gsSP2Triangles(0, 1, 2, 0, 0, 2, 3, 0),
    gsSPEndDisplayList(),
