    gsSPMatrix(0x0D000000, G_MTX_NOPUSH | G_MTX_LOAD | G_MTX_MODELVIEW),
    gsSPTexture(0x0BB8, 0x0BB8, 0, G_TX_RENDERTILE, G_ON),
    gsSPSetGeometryMode(G_LIGHTING),
    gsSPSetGeometryMode(G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR),
    gsSPVertex(&object_ik_transform_Vtx_01A1E8[0], 2, 0),
    gsSPVertex(&object_ik_transform_Vtx_01A1E8[3], 1, 3),
    gsSPVertex(&object_ik_transform_Vtx_01A1E8[5], 1, 5),
    gsSPTexture(0xFFFF, 0xFFFF, 0, G_TX_RENDERTILE, G_ON),
    gsSPClearGeometryMode(G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR),
    gsSPVertex(&object_ik_transform_Vtx_01A1E8[2], 1, 2),
    gsSPVertex(&object_ik_transform_Vtx_01A1E8[4], 1, 4),
    gsSPVertex(&object_ik_transform_Vtx_01A1E8[6], 9, 6),
    gsSPMatrix(0x0D000040, G_MTX_NOPUSH | G_MTX_LOAD | G_MTX_MODELVIEW),
    gsSPTexture(0x0BB8, 0x0BB8, 0, G_TX_RENDERTILE, G_ON),
    gsDPPipeSync(),
    gsDPSetTextureLUT(G_TT_NONE),
    gsDPSetRenderMode(G_RM_PASS, G_RM_IK_TRANSFORM_XLU_SURF2),
    gsDPSetCombineLERP(PRIMITIVE, ENVIRONMENT, TEXEL0, ENVIRONMENT, 0, 0, 0, ENVIRONMENT, COMBINED, 0, SHADE, 0, 0, 0, 0, COMBINED),
    gsSPDisplayList(0x08000000),
    gsDPLoadTextureBlock(gIronKnuckleTransformMetalTex, G_IM_FMT_I, G_IM_SIZ_8b, gIronKnuckleTransformMetalTex_WIDTH,
 gIronKnuckleTransformMetalTex_HEIGHT, 0, G_TX_MIRROR | G_TX_WRAP, G_TX_MIRROR | G_TX_WRAP, 5, 6, G_TX_NOLOD, G_TX_NOLOD),
    gsDPSetTileSize(G_TX_RENDERTILE, 0, 0, 0x007C, 0x00FC),
    gsSPClearGeometryMode(G_CULL_BACK),
    gsSPSetGeometryMode(G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR),
    gsSPVertex(&object_ik_transform_Vtx_01A1E8[15], 7, 15),
    gsSP2Triangles(5, 15, 3, 0, 16, 5, 0, 0),
    gsSPTexture(0x0BB8, 0x0BB8, 0, G_TX_RENDERTILE, G_ON),
    gsDPPipeSync(),
    gsDPSetTextureLUT(G_TT_NONE),
    gsDPSetCombineLERP(PRIMITIVE, ENVIRONMENT, TEXEL0, ENVIRONMENT, 0, 0, 0, ENVIRONMENT, COMBINED, 0, SHADE, 0, 0, 0, 0, COMBINED),
    gsSPDisplayList(0x09000000),
    gsDPLoadTextureBlock(gIronKnuckleTransformMetalTex, G_IM_FMT_I, G_IM_SIZ_8b, gIronKnuckleTransformMetalTex_WIDTH,
 gIronKnuckleTransformMetalTex_HEIGHT, 0, G_TX_MIRROR | G_TX_WRAP, G_TX_MIRROR | G_TX_WRAP, 5, 6, G_TX_NOLOD, G_TX_NOLOD),
    gsDPSetTileSize(G_TX_RENDERTILE, 0, 0, 0x007C, 0x00FC),
    gsSP2Triangles(0, 1, 17, 0, 18, 19, 1, 0),
    gsSP1Triangle(3, 20, 21, 0),
    gsSPTexture(0xFFFF, 0xFFFF, 0, G_TX_RENDERTILE, G_ON),
    gsDPPipeSync(),
    gsDPSetRenderMode(G_RM_FOG_SHADE_A, G_RM_IK_TRANSFORM_XLU_SURF2),
    gsDPSetCombineLERP(TEXEL0, 0, SHADE, 0, 0, 0, 0, ENVIRONMENT, PRIMITIVE, 0, COMBINED, 0, 0, 0, 0, COMBINED),
    gsDPSetTextureLUT(G_TT_NONE),
    gsDPLoadTextureBlock(gIronKnuckleTransformChainMailTex, G_IM_FMT_RGBA, G_IM_SIZ_16b, gIronKnuckleTransformChainMailTex_WIDTH,
 gIronKnuckleTransformChainMailTex_HEIGHT, 0, G_TX_NOMIRROR | G_TX_WRAP, G_TX_NOMIRROR | G_TX_CLAMP, 4, 4, G_TX_NOLOD,
 G_TX_NOLOD),
    gsDPSetTileSize(G_TX_RENDERTILE, 0, 0, 0x003C, 0x003C),
    gsDPSetPrimColor(0, 0x80, 255, 255, 255, 255),
    gsSPClearGeometryMode(G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR),
    gsSPVertex(&object_ik_transform_Vtx_01A1E8[22], 7, 15),
    gsSP2Triangles(15, 16, 10, 0, 10, 7, 17, 0),
    gsDPPipeSync(),
    gsDPSetTextureLUT(G_TT_NONE),
    gsDPLoadTextureBlock(gIronKnuckleTransformBlockPatternTex, G_IM_FMT_RGBA, G_IM_SIZ_16b, gIronKnuckleTransformBlockPatternTex_WIDTH,
 gIronKnuckleTransformBlockPatternTex_HEIGHT, 0, G_TX_NOMIRROR | G_TX_WRAP, G_TX_NOMIRROR | G_TX_CLAMP, 4, 4, G_TX_NOLOD,
 G_TX_NOLOD),
    gsDPSetTileSize(G_TX_RENDERTILE, 0, 0, 0x003C, 0x003C),
    gsDPSetPrimColor(0, 0x80, 255, 255, 255, 255),
    gsSP2Triangles(8, 9, 4, 0, 4, 18, 8, 0),
    gsDPPipeSync(),
    gsDPSetTextureLUT(G_TT_NONE),
    gsDPLoadTextureBlock(gIronKnuckleTransformChainMailTex, G_IM_FMT_RGBA, G_IM_SIZ_16b, gIronKnuckleTransformChainMailTex_WIDTH,
 gIronKnuckleTransformChainMailTex_HEIGHT, 0, G_TX_NOMIRROR | G_TX_WRAP, G_TX_NOMIRROR | G_TX_CLAMP, 4, 4, G_TX_NOLOD,
 G_TX_NOLOD),
    gsDPSetTileSize(G_TX_RENDERTILE, 0, 0, 0x003C, 0x003C),
    gsDPSetPrimColor(0, 0x80, 255, 255, 255, 255),
    gsSP1Triangle(2, 6, 19, 0),
    gsDPPipeSync(),
    gsDPSetRenderMode(G_RM_FOG_SHADE_A, G_RM_IK_TRANSFORM_XLU_SURF2),
    gsDPSetTextureLUT(G_TT_NONE),
    gsDPLoadTextureBlock(object_ik_transform_Tex_01DBA8, G_IM_FMT_IA, G_IM_SIZ_16b, object_ik_transform_Tex_01DBA8_WIDTH,
 object_ik_transform_Tex_01DBA8_HEIGHT, 0, G_TX_NOMIRROR | G_TX_CLAMP, G_TX_NOMIRROR | G_TX_WRAP, 4, 4, G_TX_NOLOD, G_TX_NOLOD),
    gsDPSetTileSize(G_TX_RENDERTILE, 0, 0, 0x003C, 0x003C),
    gsDPSetPrimColor(0, 0x80, 255, 255, 255, 255),
    gsSPSetGeometryMode(G_CULL_BACK),
    gsSP1Triangle(20, 14, 12, 0),
    gsDPSetPrimColor(0, 0x80, 255, 255, 255, 255),
    gsSP1Triangle(11, 21, 13, 0),
    gsSPTexture(0x0BB8, 0x0BB8, 0, G_TX_RENDERTILE, G_ON),
    gsDPPipeSync(),
    gsDPSetTextureLUT(G_TT_NONE),
    gsDPSetRenderMode(G_RM_PASS, G_RM_IK_TRANSFORM_XLU_SURF2),
    gsDPSetCombineLERP(PRIMITIVE, ENVIRONMENT, TEXEL0, ENVIRONMENT, 0, 0, 0, ENVIRONMENT, COMBINED, 0, SHADE, 0, 0, 0, 0, COMBINED),
    gsSPDisplayList(0x09000000),
    gsDPLoadTextureBlock(gIronKnuckleTransformMetalTex, G_IM_FMT_I, G_IM_SIZ_8b, gIronKnuckleTransformMetalTex_WIDTH,
 gIronKnuckleTransformMetalTex_HEIGHT, 0, G_TX_MIRROR | G_TX_WRAP, G_TX_MIRROR | G_TX_WRAP, 5, 6, G_TX_NOLOD, G_TX_NOLOD),
    gsDPSetTileSize(G_TX_RENDERTILE, 0, 0, 0x007C, 0x00FC),
    gsSPClearGeometryMode(G_CULL_BACK),
    gsSPSetGeometryMode(G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR),
    gsSPVertex(&object_ik_transform_Vtx_01A1E8[29], 4, 0),
    gsSP2Triangles(0, 1, 2, 0, 2, 1, 3, 0),
    gsSPEndDisplayList(),
