    gsSPTexture(0x0BB8, 0x0BB8, 0, G_TX_RENDERTILE, G_ON),
    gsDPPipeSync(),
    gsDPSetTextureLUT(G_TT_NONE),
    gsDPSetRenderMode(G_RM_PASS, G_RM_AA_ZB_XLU_SURF2),
    gsDPSetCombineLERP(PRIMITIVE, ENVIRONMENT, TEXEL0, ENVIRONMENT, TEXEL0, 0, ENVIRONMENT, 0, COMBINED, 0, SHADE, 0, 0, 0, 0, COMBINED),
    gsSPDisplayList(0x08000000),
    gsDPLoadTextureBlock(gIronKnuckleTransformMetalTex, G_IM_FMT_I, G_IM_SIZ_8b, gIronKnuckleTransformMetalTex_WIDTH,
 gIronKnuckleTransformMetalTex_HEIGHT, 0, G_TX_MIRROR | G_TX_WRAP, G_TX_MIRROR | G_TX_WRAP, 5, 6, G_TX_NOLOD, G_TX_NOLOD),
    gsDPSetTileSize(G_TX_RENDERTILE, 0, 0, 0x007C, 0x00FC),
    gsSPSetGeometryMode(G_LIGHTING),
    gsSPSetGeometryMode(G_CULL_BACK),
    gsSPSetGeometryMode(G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR),
    gsSPVertex(&object_ik_transform_Vtx_01A0F8[0], 15, 0),
    gsSP2Triangles(0, 1, 2, 0, 2, 1, 3, 0),
    gsSP2Triangles(2, 3, 4, 0, 5, 1, 0, 0),
    gsSP2Triangles(0, 6, 5, 0, 4, 3, 5, 0),
    gsSP1Triangle(5, 6, 4, 0),
    gsSPTexture(0x0BB8, 0x0BB8, 0, G_TX_RENDERTILE, G_ON),
    gsDPPipeSync(),
    gsDPSetTextureLUT(G_TT_NONE),
    gsDPSetCombineLERP(PRIMITIVE, ENVIRONMENT, TEXEL0, ENVIRONMENT, TEXEL0, 0, ENVIRONMENT, 0, COMBINED, 0, SHADE, 0, 0, 0, 0, COMBINED),
    gsSPDisplayList(0x09000000),
    gsDPLoadTextureBlock(gIronKnuckleTransformMetalTex, G_IM_FMT_I, G_IM_SIZ_8b, gIronKnuckleTransformMetalTex_WIDTH,
 gIronKnuckleTransformMetalTex_HEIGHT, 0, G_TX_MIRROR | G_TX_WRAP, G_TX_MIRROR | G_TX_WRAP, 5, 6, G_TX_NOLOD, G_TX_NOLOD),
    gsDPSetTileSize(G_TX_RENDERTILE, 0, 0, 0x007C, 0x00FC),
    gsSP2Triangles(7, 8, 9, 0, 9, 10, 11, 0),
    gsSP2Triangles(12, 13, 11, 0, 12, 8, 7, 0),
    gsSP2Triangles(9, 14, 7, 0, 11, 14, 9, 0),
    gsSP2Triangles(7, 13, 12, 0, 11, 10, 12, 0),
    gsSP1Triangle(12, 10, 8, 0),
    gsSPEndDisplayList(),
