#define BOOT_TO_SCENE
// #define BOOT_TO_SCENE_NEW_GAME_ONLY
// #define BOOT_TO_FILE_SELECT
// #define BOOT_TO_MAP_SELECT
#define BOOT_ENTRANCE ENTR_HM_JAM_DUNG_0
#define BOOT_AGE LINK_AGE_CHILD
#define BOOT_TIME NEXT_TIME_NONE
#define BOOT_CUTSCENE 0xFFEF
#define BOOT_PLAYER_NAME 0x15, 0x2C, 0x31, 0x2E, 0x3E, 0x3E, 0x3E, 0x3E

