    &gObjectGolBabyRoot1Limb, // 0
    &gObjectGolBabyRoot2Limb, // 1
    &gObjectGolBabyBodyLimb, // 2
    &gObjectGolBabyAntennaRoot1Limb, // 3
    &gObjectGolBabyAntennaRoot2Limb, // 4
    &gObjectGolBabyAntennaLimb, // 5
    &gObjectGolBabyEyeIrisRoot1Limb, // 6
    &gObjectGolBabyEyeIrisRoot2Limb, // 7
    &gObjectGolBabyEyeIrisLimb, // 8
    &gObjectGolBabyLeftLegRoot1Limb, // 9
    &gObjectGolBabyLeftLegRoot2Limb, // 10
    &gObjectGolBabyLeftShinRootLimb, // 11
    &gObjectGolBabyLeftFootRootLimb, // 12
    &gObjectGolBabyLeftFootLimb, // 13
    &gObjectGolBabyLeftShinLimb, // 14
    &gObjectGolBabyLeftThighLimb, // 15
    &gObjectGolBabyRightLegRoot1Limb, // 16
    &gObjectGolBabyRightLegRoot2Limb, // 17
    &gObjectGolBabyRightShinRootLimb, // 18
    &gObjectGolBabyRightFootRootLimb, // 19
    &gObjectGolBabyRightFootLimb, // 20
    &gObjectGolBabyRightShinLimb, // 21
    &gObjectGolBabyRightThighLimb, // 22

